export { default as Dashboard } from './pages/Dashboard'
export { default as Login } from './pages/Login'
export { default as Students } from './pages/Students'
export { default as Tournaments } from './pages/Tournaments'
export { default as Enrollments } from './pages/Enrollments'